travis:
  secure:
    BINSTAR_TOKEN: SMnKklSjcwcgA+14vJhjVG+l1D+L6QJTtPDpWwe/CxNvROhdjHblc2iqVeZyrQhBIGJI2zOIJ8SWCgmE3vqTPTLLQetrIsIfJNSk7ic/TAA990Wazwt4pA/N8zGLcpIfKw5xBR1qaZRllTaHLJYndP5fLIb//2zVtVsNV0Vl9MDHsQqTHT1qd+CtY+WBNEz/ad4cJ84tUZhV1HogmKmxzTScCIGHqc7YzYIvtOrFZJg+DYarpAfSluLeF7bfPpFUfoCWOvpIMLz6+bDZFaU6FSZf66yAI6oiiRrnegb7iIB1ILKq+dkyxjPYLYDjIrBnmtVBQhSpqoUFMwzphdaTONK7JN7cCTj8ipClLabfGFP/X4HNGs2uoE8h9GE4k2mS6iqJcBOY7bL3LkvwjuUu3j5ae21uwjbKxViqGpIv3KKs387VZMDDESAsSObCUOytV77wrITWUnXd56c68OtRbHewVeC1pxS7X4Kgfhk34dx9jJxPXYsqnXnmP4yfZFGlKh4ZAVvKA3f3FPOWY34XkPtOsf780eKLJWm8tHHBzrGav3xjKdyxqn9Ug3SYAHPPUnzqkMu9au4To1PaXWCJYwh6w+A0OLwhky29PwDXwoXuUC8JP+/QLieHVd7d+gatjfuGD1K60Rgj5sOd6HV4+xgb4YJQoD8XxY3T8600RJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
