travis:
  secure:
    BINSTAR_TOKEN: BXYFBcCkqGMQdikixipKi7tj7EI4AS9tAGXp0pq3qDqr1ACHlEilXUrCbASsZXPdkcHMFMLJk7NbPQfYKfr2VdxVVcJzMaf4BqddQ1VLLSU7/eUXaFy3XL4sqeQtDxlwND+eaqow/MXyoBjM5zup4wjPxEoyOaEnQNouhEUj7vCphTaqu/+5bcsP0KHs4CrheIKDLvfHfobSwQSmGLcagdhHPWEFUnUHau61Efhe4mZ7YJd3u97oUO/FgmtnXMSEe1sjrNq5B+ngzgfxqNnVRILp5waT9okkFzHTPPQ8LVSzs5/48jhUETcg6veaspwpioQQ3uEXNPE0tnQImv4zi7KnVF5cZww61gjtYZEa5O9w6+pRetksHe+oypZWRdlfPx8stESuPD/a+alPfXQMybFDqGzBSkx/rFuznqVcGzn+QsB8B9ct7JdR92txEyEIk1tstRSfa1uchEWg2FbJc5eeWq2TVCYYxsrJVjbVeet4BdtQxfKPCAx93E71ieCoyxMEYgIqyWN0oI4Hvy9jNnnZhMWY+AxigBHpoHoKey1q7ImY5szlLEtSoRav8vQPIZQJAbLk9PmPC91b4xWkre8H3OUemOZkYnPewbADNQYTltOVzd4ve8nx91QHird7qU/BFiDkKc0IjxmZo9kYtaYqgkF0ZNakaLKAKgDXWAU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
